version: "3"

services:
    php-fpm-debian:
        build:
            context: debian
        restart: unless-stopped
        cpu_count: 1
        cpu_percent: 50
        mem_limit: 256m
        mem_swappiness: 0
        environment:
            HOSTNAME: debian

    php-fpm-official:
        build:
            context: official
        restart: unless-stopped
        cpu_count: 1
        cpu_percent: 50
        mem_limit: 256m
        mem_swappiness: 0
        environment:
            HOSTNAME: official

    php-fpm-phpdockerio:
        build:
            context: phpdockerio
        restart: unless-stopped
        cpu_count: 1
        cpu_percent: 50
        mem_limit: 256m
        mem_swappiness: 0
        environment:
            HOSTNAME: phpdockerio

    php-fpm-nami:
        build:
            context: nami
        restart: unless-stopped
        cpu_count: 1
        cpu_percent: 50
        mem_limit: 256m
        mem_swappiness: 0
        environment:
            HOSTNAME: nami

    web:
        image: nginx:alpine
        restart: unless-stopped
        cpu_count: 1
        cpu_percent: 50
        mem_limit: 256m
        mem_swappiness: 0
        volumes:
            - "./debian/nginx.conf:/etc/nginx/conf.d/default.conf"
            - "./debian/app:/app/debian"
            - "./debian/nginx.conf:/etc/nginx/conf.d/debian.conf"
            - "./official/app:/app/official"
            - "./official/nginx.conf:/etc/nginx/conf.d/official.conf"
            - "./phpdockerio/app:/app/phpdockerio"
            - "./phpdockerio/nginx.conf:/etc/nginx/conf.d/phpdockerio.conf"
            - "./nami/app:/app/nami"
            - "./nami/nginx.conf:/etc/nginx/conf.d/nami.conf"

    bench:
        image: docker.io/library/php:7-fpm
        volumes:
            - "./compare.php:/app/compare.php"
